import { mkdir, rename } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { writeFileSync } from 'node:fs';

import { fetchSessionInfo } from './transmission';
import type { TransmissionConfig } from './config';
import {
  activeProfilePath,
  credentialsPath,
  readVpnManifest,
  vpnDir,
  writeVpnManifest,
  type VpnManifest,
} from './vpn-state';
import { readConfigFileRecord, writeConfigAtomically } from './api';

// Gluetun OpenVPN health endpoint — confirmed against gluetun HTTP API docs.
// GET /v1/openvpn/status returns { status: 'running' | 'stopped' }.
// The more general /v1/vpn/status covers WireGuard too (v2 path).
const GLUETUN_HEALTH_URL = 'http://gluetun:8000/v1/openvpn/status';

export type VpnVerifyStatus =
  | 'vpn_bridge_active'
  | 'vpn_bridge_unreachable'
  | 'passthrough';

export type VpnApiDeps = {
  configPath: string;
  writeToken: string | undefined;
  transmissionConfig: TransmissionConfig;
};

function parseBearerToken(header: string | null): string | null {
  if (!header) return null;
  const [scheme, token] = header.split(' ');
  if (scheme?.toLowerCase() !== 'bearer' || !token) return null;
  return token;
}

function checkWriteAuth(
  request: Request,
  writeToken: string | undefined,
): Response | null {
  if (!writeToken) {
    return Response.json(
      { error: 'config writes are disabled' },
      { status: 403 },
    );
  }
  const bearer = parseBearerToken(request.headers.get('authorization'));
  if (!bearer) {
    return Response.json({ error: 'missing bearer token' }, { status: 401 });
  }
  if (bearer !== writeToken) {
    return Response.json({ error: 'forbidden' }, { status: 403 });
  }
  return null;
}

async function readTrustedOrigins(configDir: string): Promise<string[]> {
  const file = Bun.file(join(configDir, 'web', 'trusted-origins.json'));
  if (!(await file.exists())) return [];
  try {
    const raw: unknown = await file.json();
    if (!Array.isArray(raw)) return [];
    return (raw as unknown[]).filter((x): x is string => typeof x === 'string');
  } catch {
    return [];
  }
}

function composePath(configDir: string): string {
  return join(vpnDir(configDir), 'compose.synology.yml');
}

export async function generateComposeArtifact(
  configDir: string,
): Promise<void> {
  const trustedOrigins = await readTrustedOrigins(configDir);
  const allowedOrigins = trustedOrigins.join(' ');
  const origin = trustedOrigins[0] ?? '';
  const outPath = composePath(configDir);

  const yaml =
    [
      '# Generated by Pirate Claw — do not edit manually',
      '# Re-generated on every VPN profile or credential save.',
      'name: pirate-claw-synology',
      '',
      'x-install-root: &install-root ${PIRATE_CLAW_INSTALL_ROOT:-/volume1/pirate-claw}',
      'x-container-install-root: &container-install-root /volume1/pirate-claw',
      'x-daemon-token-file: &daemon-token-file /volume1/pirate-claw/config/generated/daemon-api-write-token',
      '',
      'services:',
      '  gluetun:',
      '    image: qmcgaw/gluetun:latest',
      '    restart: unless-stopped',
      '    cap_add:',
      '      - NET_ADMIN',
      '    network_mode: bridge',
      '    devices:',
      '      - /dev/net/tun:/dev/net/tun',
      '    volumes:',
      '      - type: bind',
      '        source: *install-root',
      '        target: /volume1/pirate-claw',
      '    environment:',
      '      VPN_SERVICE_PROVIDER: custom',
      '      VPN_TYPE: openvpn',
      '      OPENVPN_CUSTOM_CONFIG: /volume1/pirate-claw/config/vpn/active-profile.ovpn',
      '      OPENVPN_CREDS: /volume1/pirate-claw/config/vpn/credentials',
      '      HTTP_CONTROL_SERVER_ADDRESS: :8000',
      '    ports:',
      "      - '8888:8888'",
      "      - '9091:9091'",
      '',
      '  pirate-claw-daemon:',
      '    image: pirate-claw:latest',
      '    build:',
      '      context: .',
      '      dockerfile: Dockerfile',
      "    entrypoint: ['bun', 'run', '/app/dist/cli.js']",
      '    command:',
      '      [',
      "        'daemon',",
      "        '--config',",
      "        '/volume1/pirate-claw/config/pirate-claw.config.json',",
      '      ]',
      '    working_dir: /volume1/pirate-claw/data',
      '    restart: unless-stopped',
      '    environment:',
      '      PIRATE_CLAW_INSTALL_ROOT: *container-install-root',
      '      PIRATE_CLAW_API_HOST: 0.0.0.0',
      "      PIRATE_CLAW_API_PORT: '5555'",
      '      PIRATE_CLAW_TRANSMISSION_URL: http://transmission:9091/transmission/rpc',
      '    expose:',
      "      - '5555'",
      '    volumes:',
      '      - type: bind',
      '        source: *install-root',
      '        target: /volume1/pirate-claw',
      '    depends_on:',
      '      - gluetun',
      '    network_mode: service:gluetun',
      '',
      '  pirate-claw-web:',
      '    image: pirate-claw-web:latest',
      '    build:',
      '      context: .',
      '      dockerfile: web/Dockerfile',
      '    command:',
      '      - sh',
      '      - -c',
      '      - |',
      '        while [ ! -s "$$PIRATE_CLAW_DAEMON_TOKEN_FILE" ]; do sleep 1; done',
      '        export PIRATE_CLAW_API_WRITE_TOKEN="$$(cat "$$PIRATE_CLAW_DAEMON_TOKEN_FILE")"',
      '        exec node build',
      '    restart: unless-stopped',
      '    environment:',
      '      HOST: 0.0.0.0',
      "      PORT: '8888'",
      '      PIRATE_CLAW_API_URL: http://pirate-claw-daemon:5555',
      '      PIRATE_CLAW_DAEMON_TOKEN_FILE: *daemon-token-file',
      `      ALLOWED_ORIGINS: '${allowedOrigins}'`,
      `      ORIGIN: '${origin}'`,
      '    volumes:',
      '      - type: bind',
      '        source: *install-root',
      '        target: /volume1/pirate-claw',
      '        read_only: true',
      '    depends_on:',
      '      - pirate-claw-daemon',
      '    network_mode: service:gluetun',
      '',
      '  transmission:',
      '    image: lscr.io/linuxserver/transmission:latest',
      '    restart: unless-stopped',
      '    environment:',
      '      PUID: ${PIRATE_CLAW_TRANSMISSION_PUID:-0}',
      '      PGID: ${PIRATE_CLAW_TRANSMISSION_PGID:-0}',
      '      TZ: UTC',
      '    expose:',
      "      - '9091'",
      '    volumes:',
      '      - type: bind',
      '        source: ${PIRATE_CLAW_INSTALL_ROOT:-/volume1/pirate-claw}/transmission/config',
      '        target: /config',
      '      - type: bind',
      '        source: ${PIRATE_CLAW_INSTALL_ROOT:-/volume1/pirate-claw}/downloads',
      '        target: /downloads',
      '      - type: bind',
      '        source: ${PIRATE_CLAW_INSTALL_ROOT:-/volume1/pirate-claw}/downloads/incomplete',
      '        target: /incomplete-downloads',
      '      - type: bind',
      '        source: ${PIRATE_CLAW_INSTALL_ROOT:-/volume1/pirate-claw}/media',
      '        target: /media',
      '    network_mode: service:gluetun',
    ].join('\n') + '\n';

  await mkdir(vpnDir(configDir), { recursive: true });
  const tempPath = `${outPath}.${process.pid}.${randomUUID()}.tmp`;
  writeFileSync(tempPath, yaml, { encoding: 'utf8', flag: 'wx' });
  await rename(tempPath, outPath);
  console.log(
    `[compose] artifact generated — trustedOrigins: ${String(trustedOrigins.length)}; path: ${outPath}`,
  );
}

async function handleProfileUpload(
  request: Request,
  configDir: string,
  configPath: string,
): Promise<Response> {
  const bytes = await request.arrayBuffer();
  if (bytes.byteLength === 0) {
    return Response.json({ error: 'Request body is empty.' }, { status: 400 });
  }
  const text = new TextDecoder()
    .decode(new Uint8Array(bytes).slice(0, 16))
    .trimStart();
  const isValidOvpn = text.startsWith('client') || text.startsWith('proto');
  if (!isValidOvpn) {
    return Response.json(
      { error: 'Invalid .ovpn file: must begin with "client" or "proto".' },
      { status: 400 },
    );
  }

  await mkdir(vpnDir(configDir), { recursive: true });
  const profilePath = activeProfilePath(configDir);
  const tempPath = `${profilePath}.${process.pid}.${randomUUID()}.tmp`;
  writeFileSync(tempPath, new Uint8Array(bytes));
  await rename(tempPath, profilePath);

  const existingManifest = await readVpnManifest(configDir);
  const manifest: VpnManifest = {
    uploadedAt: new Date().toISOString(),
    provider: 'custom',
    hasCredentials: existingManifest?.hasCredentials ?? false,
  };
  await writeVpnManifest(configDir, manifest);

  // update config downloaderNetwork
  const baseOnDisk = await readConfigFileRecord(configPath);
  const existingDn =
    baseOnDisk.downloaderNetwork &&
    typeof baseOnDisk.downloaderNetwork === 'object' &&
    !Array.isArray(baseOnDisk.downloaderNetwork)
      ? (baseOnDisk.downloaderNetwork as Record<string, unknown>)
      : {};
  writeConfigAtomically(configPath, {
    ...baseOnDisk,
    downloaderNetwork: {
      ...existingDn,
      mode: 'vpn_bridge',
      status: 'pending_verify',
    },
  });

  await generateComposeArtifact(configDir);
  console.log(
    `[vpn] profile saved — size: ${String(bytes.byteLength)}; compose artifacts regenerated`,
  );
  return Response.json({ ok: true, manifest });
}

async function handleCredentialsSave(
  request: Request,
  configDir: string,
): Promise<Response> {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: 'Request body must be JSON.' },
      { status: 400 },
    );
  }
  if (
    !body ||
    typeof body !== 'object' ||
    Array.isArray(body) ||
    typeof (body as Record<string, unknown>).username !== 'string' ||
    typeof (body as Record<string, unknown>).password !== 'string'
  ) {
    return Response.json(
      { error: 'Body must be { username: string, password: string }.' },
      { status: 400 },
    );
  }
  const { username, password } = body as { username: string; password: string };
  if (!username.trim() || !password.trim()) {
    return Response.json(
      { error: 'username and password must be non-empty strings.' },
      { status: 400 },
    );
  }

  await mkdir(vpnDir(configDir), { recursive: true });
  const credsPath = credentialsPath(configDir);
  const credsContent = `${username}\n${password}\n`;
  writeFileSync(credsPath, credsContent, { encoding: 'utf8', mode: 0o600 });

  const existingManifest = await readVpnManifest(configDir);
  const manifest: VpnManifest = {
    uploadedAt: existingManifest?.uploadedAt ?? new Date().toISOString(),
    provider: existingManifest?.provider ?? 'custom',
    hasCredentials: true,
  };
  await writeVpnManifest(configDir, manifest);

  await generateComposeArtifact(configDir);
  console.log(
    `[vpn] credentials saved (username: ${username}); compose artifacts regenerated`,
  );
  return Response.json({ ok: true });
}

async function handleComposeServe(configDir: string): Promise<Response> {
  const path = composePath(configDir);
  const file = Bun.file(path);
  if (!(await file.exists())) {
    console.log('[vpn] compose artifact requested — not found');
    return Response.json(
      { error: 'No VPN profile saved yet. Upload a profile first.' },
      { status: 404 },
    );
  }
  console.log('[vpn] compose artifact served');
  const text = await file.text();
  return new Response(text, {
    headers: {
      'Content-Type': 'application/yaml',
      'Content-Disposition': 'attachment; filename=compose.synology.yml',
    },
  });
}

async function handleVerify(
  configDir: string,
  transmissionConfig: TransmissionConfig,
): Promise<Response> {
  const manifest = await readVpnManifest(configDir);
  if (!manifest?.hasCredentials) {
    console.log('[vpn] verify — no credentials saved; result: passthrough');
    return Response.json({ status: 'passthrough' satisfies VpnVerifyStatus });
  }

  let gluetunOk = false;
  let gluetunDetail = 'ok';
  let transmissionOk = false;
  let transmissionDetail = 'ok';

  try {
    const gluetunRes = await fetch(GLUETUN_HEALTH_URL, {
      signal: AbortSignal.timeout(10_000),
    });
    gluetunOk = gluetunRes.ok;
    if (!gluetunOk) gluetunDetail = `http ${String(gluetunRes.status)}`;
  } catch (err) {
    gluetunDetail = `error: ${err instanceof Error ? err.message : String(err)}`;
  }

  try {
    const result = await fetchSessionInfo(transmissionConfig);
    if (!('ok' in result) || result.ok !== false) {
      transmissionOk = true;
    } else {
      transmissionDetail = `error: ${result.message}`;
    }
  } catch (err) {
    transmissionDetail = `error: ${err instanceof Error ? err.message : String(err)}`;
  }

  const status: VpnVerifyStatus =
    gluetunOk && transmissionOk
      ? 'vpn_bridge_active'
      : 'vpn_bridge_unreachable';

  console.log(
    `[vpn] verify — gluetun: ${gluetunDetail}; transmission: ${transmissionDetail}; result: ${status}`,
  );
  return Response.json({ status });
}

export async function handleVpnRoute(
  request: Request,
  deps: VpnApiDeps,
): Promise<Response | null> {
  const { configPath, writeToken, transmissionConfig } = deps;
  const configDir = configPath.replace(/\/[^/]+$/, '');
  const url = new URL(request.url);
  const path = url.pathname;

  if (path === '/api/vpn/profile' && request.method === 'POST') {
    const authError = checkWriteAuth(request, writeToken);
    if (authError) return authError;
    return handleProfileUpload(request, configDir, configPath);
  }

  if (path === '/api/vpn/credentials' && request.method === 'POST') {
    const authError = checkWriteAuth(request, writeToken);
    if (authError) return authError;
    return handleCredentialsSave(request, configDir);
  }

  if (path === '/api/vpn/compose' && request.method === 'GET') {
    return handleComposeServe(configDir);
  }

  if (path === '/api/vpn/verify' && request.method === 'POST') {
    const authError = checkWriteAuth(request, writeToken);
    if (authError) return authError;
    return handleVerify(configDir, transmissionConfig);
  }

  return null;
}
